import { IQuestion } from "./interfaces/interface";

export const questions = [
  {
    question: "What is the capital city of Australia?",
    answer: "Canberra",
    category: "Geography",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "Which planet is known as the Red Planet?",
    answer: "Mars",
    category: "Science",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "Who developed the theory of relativity?",
    answer: "Albert Einstein",
    category: "Science",
    difficulty: "hard",
    used: false,
    reward_amount: 250,
  },
  {
    question:
      "How many players are there in a standard soccer team on the field?",
    answer: "11",
    category: "Sports",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "In which year did World War I begin?",
    answer: "1914",
    category: "History",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "What is the largest mammal on Earth?",
    answer: "Blue Whale",
    category: "Animals",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "What is the hardest natural substance on Earth?",
    answer: "Diamond",
    category: "Science",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "Who painted the Mona Lisa?",
    answer: "Leonardo da Vinci",
    category: "Art",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "What is the smallest country in the world?",
    answer: "Vatican City",
    category: "Geography",
    difficulty: "hard",
    used: false,
    reward_amount: 250,
  },
  {
    question: "What is the square root of 144?",
    answer: "12",
    category: "Math",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "Which language has the most native speakers worldwide?",
    answer: "Mandarin Chinese",
    category: "Language",
    difficulty: "hard",
    used: false,
    reward_amount: 250,
  },
  {
    question: "What is the capital of Egypt?",
    answer: "Cairo",
    category: "Geography",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "Which scientist proposed the laws of motion?",
    answer: "Isaac Newton",
    category: "Science",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "In which year did the Berlin Wall fall?",
    answer: "1989",
    category: "History",
    difficulty: "hard",
    used: false,
    reward_amount: 250,
  },
  {
    question: "Which element has the chemical symbol 'O'?",
    answer: "Oxygen",
    category: "Science",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "Who was the first man to step on the Moon?",
    answer: "Neil Armstrong",
    category: "History",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "Which country has the most islands?",
    answer: "Sweden",
    category: "Geography",
    difficulty: "hard",
    used: false,
    reward_amount: 250,
  },
  {
    question: "What is the national sport of Japan?",
    answer: "Sumo wrestling",
    category: "Sports",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "Which famous scientist discovered penicillin?",
    answer: "Alexander Fleming",
    category: "Science",
    difficulty: "hard",
    used: false,
    reward_amount: 250,
  },
  {
    question: "What is the capital of Canada?",
    answer: "Ottawa",
    category: "Geography",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "Who wrote '1984'?",
    answer: "George Orwell",
    category: "Literature",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "What is the longest river in the world?",
    answer: "Nile River",
    category: "Geography",
    difficulty: "hard",
    used: false,
    reward_amount: 250,
  },
  {
    question: "How many days are there in a leap year?",
    answer: "366",
    category: "General Knowledge",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "Which blood type is known as the universal donor?",
    answer: "O negative",
    category: "Science",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "Who was the first female Prime Minister of the UK?",
    answer: "Margaret Thatcher",
    category: "History",
    difficulty: "hard",
    used: false,
    reward_amount: 250,
  },
  {
    question: "Which gas do plants release during photosynthesis?",
    answer: "Oxygen",
    category: "Science",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "What is the chemical symbol for sodium?",
    answer: "Na",
    category: "Science",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "What is the tallest mountain in the world?",
    answer: "Mount Everest",
    category: "Geography",
    difficulty: "hard",
    used: false,
    reward_amount: 250,
  },
  {
    question: "Who painted 'Starry Night'?",
    answer: "Vincent van Gogh",
    category: "Art",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "Which country invented paper?",
    answer: "China",
    category: "History",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "What is the currency of South Korea?",
    answer: "Won",
    category: "Geography",
    difficulty: "hard",
    used: false,
    reward_amount: 250,
  },
  {
    question: "Which sport is known as the 'king of sports'?",
    answer: "Soccer",
    category: "Sports",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "How many bones are in the adult human body?",
    answer: "206",
    category: "Science",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "Who was the first emperor of China?",
    answer: "Qin Shi Huang",
    category: "History",
    difficulty: "hard",
    used: false,
    reward_amount: 250,
  },
  {
    question: "What is the capital of Italy?",
    answer: "Rome",
    category: "Geography",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "Which country gifted the Statue of Liberty to the USA?",
    answer: "France",
    category: "History",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "What is the largest moon in the solar system?",
    answer: "Ganymede",
    category: "Science",
    difficulty: "hard",
    used: false,
    reward_amount: 250,
  },
  {
    question: "Who is the author of 'Pride and Prejudice'?",
    answer: "Jane Austen",
    category: "Literature",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "Which year did the Titanic sink?",
    answer: "1912",
    category: "History",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "What is the capital city of Brazil?",
    answer: "Brasília",
    category: "Geography",
    difficulty: "hard",
    used: false,
    reward_amount: 250,
  },
  {
    question: "What is the process by which plants make food using sunlight?",
    answer: "Photosynthesis",
    category: "Science",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question:
      "Which scientist discovered gravity when an apple fell on his head?",
    answer: "Isaac Newton",
    category: "Science",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "Who was the first US president to resign from office?",
    answer: "Richard Nixon",
    category: "History",
    difficulty: "hard",
    used: false,
    reward_amount: 250,
  },
  {
    question: "Which country has the maple leaf on its flag?",
    answer: "Canada",
    category: "Geography",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "What is the capital of South Korea?",
    answer: "Seoul",
    category: "Geography",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "Who was the Greek god of the sea?",
    answer: "Poseidon",
    category: "Mythology",
    difficulty: "hard",
    used: false,
    reward_amount: 250,
  },
  {
    question: "What is the smallest prime number?",
    answer: "2",
    category: "Math",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "Which year did the Apollo 11 mission land on the Moon?",
    answer: "1969",
    category: "History",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "What is the deepest oceanic trench in the world?",
    answer: "Mariana Trench",
    category: "Geography",
    difficulty: "hard",
    used: false,
    reward_amount: 250,
  },
  // ... continues until 100
];
