import { IQuestion } from "./interfaces/interface";

export const questions = [
  {
    question: "What is the capital city of Australia?",
    answer: "Canberra",
    category: "Geography",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "Which planet is known as the Red Planet?",
    answer: "Mars",
    category: "Science",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "Who developed the theory of relativity?",
    answer: "Albert Einstein",
    category: "Science",
    difficulty: "hard",
    used: false,
    reward_amount: 250,
  },
  {
    question:
      "How many players are there in a standard soccer team on the field?",
    answer: "11",
    category: "Sports",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "In which year did World War I begin?",
    answer: "1914",
    category: "History",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "What is the largest mammal on Earth?",
    answer: "Blue Whale",
    category: "Animals",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "What is the hardest natural substance on Earth?",
    answer: "Diamond",
    category: "Science",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "Who painted the Mona Lisa?",
    answer: "Leonardo da Vinci",
    category: "Art",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "What is the smallest country in the world?",
    answer: "Vatican City",
    category: "Geography",
    difficulty: "hard",
    used: false,
    reward_amount: 250,
  },
  {
    question: "What is the square root of 144?",
    answer: "12",
    category: "Math",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "Which language has the most native speakers worldwide?",
    answer: "Mandarin Chinese",
    category: "Language",
    difficulty: "hard",
    used: false,
    reward_amount: 250,
  },
  {
    question: "What is the capital of Egypt?",
    answer: "Cairo",
    category: "Geography",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "Which scientist proposed the laws of motion?",
    answer: "Isaac Newton",
    category: "Science",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "In which year did the Berlin Wall fall?",
    answer: "1989",
    category: "History",
    difficulty: "hard",
    used: false,
    reward_amount: 250,
  },
  {
    question: "Which element has the chemical symbol 'O'?",
    answer: "Oxygen",
    category: "Science",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "Who was the first man to step on the Moon?",
    answer: "Neil Armstrong",
    category: "History",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "Which country has the most islands?",
    answer: "Sweden",
    category: "Geography",
    difficulty: "hard",
    used: false,
    reward_amount: 250,
  },
  {
    question: "What is the national sport of Japan?",
    answer: "Sumo wrestling",
    category: "Sports",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "Which famous scientist discovered penicillin?",
    answer: "Alexander Fleming",
    category: "Science",
    difficulty: "hard",
    used: false,
    reward_amount: 250,
  },
  {
    question: "What is the capital of Canada?",
    answer: "Ottawa",
    category: "Geography",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "Who wrote '1984'?",
    answer: "George Orwell",
    category: "Literature",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "What is the longest river in the world?",
    answer: "Nile River",
    category: "Geography",
    difficulty: "hard",
    used: false,
    reward_amount: 250,
  },
  {
    question: "How many days are there in a leap year?",
    answer: "366",
    category: "General Knowledge",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "Which blood type is known as the universal donor?",
    answer: "O negative",
    category: "Science",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "Who was the first female Prime Minister of the UK?",
    answer: "Margaret Thatcher",
    category: "History",
    difficulty: "hard",
    used: false,
    reward_amount: 250,
  },
  {
    question: "Which gas do plants release during photosynthesis?",
    answer: "Oxygen",
    category: "Science",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "What is the chemical symbol for sodium?",
    answer: "Na",
    category: "Science",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "What is the tallest mountain in the world?",
    answer: "Mount Everest",
    category: "Geography",
    difficulty: "hard",
    used: false,
    reward_amount: 250,
  },
  {
    question: "Who painted 'Starry Night'?",
    answer: "Vincent van Gogh",
    category: "Art",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "Which country invented paper?",
    answer: "China",
    category: "History",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "What is the currency of South Korea?",
    answer: "Won",
    category: "Geography",
    difficulty: "hard",
    used: false,
    reward_amount: 250,
  },
  {
    question: "Which sport is known as the 'king of sports'?",
    answer: "Soccer",
    category: "Sports",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "How many bones are in the adult human body?",
    answer: "206",
    category: "Science",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "Who was the first emperor of China?",
    answer: "Qin Shi Huang",
    category: "History",
    difficulty: "hard",
    used: false,
    reward_amount: 250,
  },
  {
    question: "What is the capital of Italy?",
    answer: "Rome",
    category: "Geography",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "Which country gifted the Statue of Liberty to the USA?",
    answer: "France",
    category: "History",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "What is the largest moon in the solar system?",
    answer: "Ganymede",
    category: "Science",
    difficulty: "hard",
    used: false,
    reward_amount: 250,
  },
  {
    question: "Who is the author of 'Pride and Prejudice'?",
    answer: "Jane Austen",
    category: "Literature",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "Which year did the Titanic sink?",
    answer: "1912",
    category: "History",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "What is the capital city of Brazil?",
    answer: "Brasília",
    category: "Geography",
    difficulty: "hard",
    used: false,
    reward_amount: 250,
  },
  {
    question: "What is the process by which plants make food using sunlight?",
    answer: "Photosynthesis",
    category: "Science",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question:
      "Which scientist discovered gravity when an apple fell on his head?",
    answer: "Isaac Newton",
    category: "Science",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "Who was the first US president to resign from office?",
    answer: "Richard Nixon",
    category: "History",
    difficulty: "hard",
    used: false,
    reward_amount: 250,
  },
  {
    question: "Which country has the maple leaf on its flag?",
    answer: "Canada",
    category: "Geography",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "What is the capital of South Korea?",
    answer: "Seoul",
    category: "Geography",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "Who was the Greek god of the sea?",
    answer: "Poseidon",
    category: "Mythology",
    difficulty: "hard",
    used: false,
    reward_amount: 250,
  },
  {
    question: "What is the smallest prime number?",
    answer: "2",
    category: "Math",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "Which year did the Apollo 11 mission land on the Moon?",
    answer: "1969",
    category: "History",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "What is the deepest oceanic trench in the world?",
    answer: "Mariana Trench",
    category: "Geography",
    difficulty: "hard",
    used: false,
    reward_amount: 250,
  },
  {
    question: "What is the capital of Argentina?",
    answer: "Buenos Aires",
    category: "Geography",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "Which organ in the human body produces insulin?",
    answer: "Pancreas",
    category: "Science",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "In Greek mythology, who is the goddess of wisdom?",
    answer: "Athena",
    category: "Mythology",
    difficulty: "hard",
    used: false,
    reward_amount: 250,
  },
  {
    question: "What is the national flower of Japan?",
    answer: "Cherry Blossom",
    category: "Culture",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "Which element is said to keep bones strong?",
    answer: "Calcium",
    category: "Science",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question:
      "Who was the first African-American president of the United States?",
    answer: "Barack Obama",
    category: "History",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "Which ancient civilization built Machu Picchu?",
    answer: "Inca",
    category: "History",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "Which chemical element has the atomic number 79?",
    answer: "Gold",
    category: "Science",
    difficulty: "hard",
    used: false,
    reward_amount: 250,
  },
  {
    question: "What is the capital of Kenya?",
    answer: "Nairobi",
    category: "Geography",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "In which year did humans first climb Mount Everest?",
    answer: "1953",
    category: "History",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "Which Italian city is famous for its leaning tower?",
    answer: "Pisa",
    category: "Geography",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "Who painted the ceiling of the Sistine Chapel?",
    answer: "Michelangelo",
    category: "Art",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "What is the capital of Thailand?",
    answer: "Bangkok",
    category: "Geography",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "What is the most abundant gas in Earth's atmosphere?",
    answer: "Nitrogen",
    category: "Science",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "What is the capital city of New Zealand?",
    answer: "Wellington",
    category: "Geography",
    difficulty: "hard",
    used: false,
    reward_amount: 250,
  },
  {
    question: "Which country is known as the Land of the Rising Sun?",
    answer: "Japan",
    category: "Geography",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "In which year did the French Revolution begin?",
    answer: "1789",
    category: "History",
    difficulty: "hard",
    used: false,
    reward_amount: 250,
  },
  {
    question: "What type of blood cells help fight infection?",
    answer: "White blood cells",
    category: "Science",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "What is the capital of Turkey?",
    answer: "Ankara",
    category: "Geography",
    difficulty: "hard",
    used: false,
    reward_amount: 250,
  },
  {
    question:
      "Which famous ship sank in 1915 after being hit by a German U-boat?",
    answer: "Lusitania",
    category: "History",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "What is the main ingredient in guacamole?",
    answer: "Avocado",
    category: "Food",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "Which Roman emperor was assassinated on the Ides of March?",
    answer: "Julius Caesar",
    category: "History",
    difficulty: "hard",
    used: false,
    reward_amount: 250,
  },
  {
    question: "Which African country is famous for its pyramids besides Egypt?",
    answer: "Sudan",
    category: "Geography",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "Who is the author of 'The Catcher in the Rye'?",
    answer: "J.D. Salinger",
    category: "Literature",
    difficulty: "hard",
    used: false,
    reward_amount: 250,
  },
  {
    question: "Which continent is the Sahara Desert located on?",
    answer: "Africa",
    category: "Geography",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "What is the main language spoken in Brazil?",
    answer: "Portuguese",
    category: "Language",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "Who was known as the 'Maid of Orléans'?",
    answer: "Joan of Arc",
    category: "History",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "Which gas is essential for human respiration?",
    answer: "Oxygen",
    category: "Science",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "What is the national animal of China?",
    answer: "Giant Panda",
    category: "Animals",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "What is the capital of Iceland?",
    answer: "Reykjavík",
    category: "Geography",
    difficulty: "hard",
    used: false,
    reward_amount: 250,
  },
  {
    question: "Who wrote the play 'Romeo and Juliet'?",
    answer: "William Shakespeare",
    category: "Literature",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "Which city hosted the 2008 Summer Olympics?",
    answer: "Beijing",
    category: "Sports",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "Who was the first woman to win a Nobel Prize?",
    answer: "Marie Curie",
    category: "History",
    difficulty: "hard",
    used: false,
    reward_amount: 250,
  },
  {
    question: "What is the capital city of Mexico?",
    answer: "Mexico City",
    category: "Geography",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "Which sea separates Europe and Africa?",
    answer: "Mediterranean Sea",
    category: "Geography",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "What is the currency of Switzerland?",
    answer: "Swiss Franc",
    category: "Geography",
    difficulty: "hard",
    used: false,
    reward_amount: 250,
  },
  {
    question: "What is the capital of Nigeria?",
    answer: "Abuja",
    category: "Geography",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "Who invented the telephone?",
    answer: "Alexander Graham Bell",
    category: "Science",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "Which planet is the hottest in our solar system?",
    answer: "Venus",
    category: "Science",
    difficulty: "hard",
    used: false,
    reward_amount: 250,
  },
  {
    question: "Which Asian country is known as the Land of the Thunder Dragon?",
    answer: "Bhutan",
    category: "Geography",
    difficulty: "hard",
    used: false,
    reward_amount: 250,
  },
  {
    question: "What is the capital of Spain?",
    answer: "Madrid",
    category: "Geography",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "Who painted the famous artwork 'The Persistence of Memory'?",
    answer: "Salvador Dalí",
    category: "Art",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "Which empire was ruled by Genghis Khan?",
    answer: "Mongol Empire",
    category: "History",
    difficulty: "hard",
    used: false,
    reward_amount: 250,
  },
  {
    question: "What is the chemical symbol for iron?",
    answer: "Fe",
    category: "Science",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "What is the capital of Sweden?",
    answer: "Stockholm",
    category: "Geography",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "What year did World War II begin?",
    answer: "1939",
    category: "History",
    difficulty: "hard",
    used: false,
    reward_amount: 250,
  },
  {
    question: "Which natural satellite orbits the Earth?",
    answer: "The Moon",
    category: "Science",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "Which Italian explorer reached the Americas in 1492?",
    answer: "Christopher Columbus",
    category: "History",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "What is the largest ocean on Earth?",
    answer: "Pacific Ocean",
    category: "Geography",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "What is the capital of Saudi Arabia?",
    answer: "Riyadh",
    category: "Geography",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question:
      "Which scientist proposed the heliocentric model of the solar system?",
    answer: "Nicolaus Copernicus",
    category: "Science",
    difficulty: "hard",
    used: false,
    reward_amount: 250,
  },
  {
    question: "Which natural disaster is measured with a Richter scale?",
    answer: "Earthquake",
    category: "Science",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "In what year did the Berlin Wall fall?",
    answer: "1989",
    category: "History",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "What is the capital of Canada?",
    answer: "Ottawa",
    category: "Geography",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "Which artist painted 'The Persistence of Memory'?",
    answer: "Salvador Dalí",
    category: "Art",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "What planet has the most moons?",
    answer: "Saturn",
    category: "Science",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "Who was the first woman to win a Nobel Prize?",
    answer: "Marie Curie",
    category: "History",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "What is the national flower of Japan?",
    answer: "Cherry Blossom",
    category: "Geography",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question:
      "Which programming language is known as the 'mother of all languages'?",
    answer: "C",
    category: "Technology",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "Which country invented paper?",
    answer: "China",
    category: "History",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "What is the chemical symbol for silver?",
    answer: "Ag",
    category: "Science",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },

  // --- 40 more unique ones ---
  {
    question: "Which ocean is the Bermuda Triangle located in?",
    answer: "Atlantic Ocean",
    category: "Geography",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "What is the hardest natural substance on Earth?",
    answer: "Diamond",
    category: "Science",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "In which country was the Titanic built?",
    answer: "Northern Ireland",
    category: "History",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "What is the square root of 256?",
    answer: "16",
    category: "Mathematics",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "Which Greek god is the god of war?",
    answer: "Ares",
    category: "Mythology",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "What does DNA stand for?",
    answer: "Deoxyribonucleic Acid",
    category: "Science",
    difficulty: "hard",
    used: false,
    reward_amount: 250,
  },
  {
    question: "Which U.S. president served the shortest term?",
    answer: "William Henry Harrison",
    category: "History",
    difficulty: "hard",
    used: false,
    reward_amount: 250,
  },
  {
    question: "Which country is known as the Land of the Rising Sun?",
    answer: "Japan",
    category: "Geography",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "Who directed the movie 'Pulp Fiction'?",
    answer: "Quentin Tarantino",
    category: "Entertainment",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "What is the largest bone in the human body?",
    answer: "Femur",
    category: "Science",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },

  {
    question: "Which planet spins backwards compared to most planets?",
    answer: "Venus",
    category: "Science",
    difficulty: "hard",
    used: false,
    reward_amount: 250,
  },
  {
    question: "Who was the first man to travel into space?",
    answer: "Yuri Gagarin",
    category: "History",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "What is the name of the largest reef system on Earth?",
    answer: "Great Barrier Reef",
    category: "Geography",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "What is the national currency of South Korea?",
    answer: "Won",
    category: "Geography",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "In computing, what does 'HTTP' stand for?",
    answer: "HyperText Transfer Protocol",
    category: "Technology",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "Which Shakespeare play features the character Shylock?",
    answer: "The Merchant of Venice",
    category: "Literature",
    difficulty: "hard",
    used: false,
    reward_amount: 250,
  },
  {
    question: "Who painted the ceiling of the Sistine Chapel?",
    answer: "Michelangelo",
    category: "Art",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "What element has the chemical symbol 'K'?",
    answer: "Potassium",
    category: "Science",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "Which animal is known as the 'King of the Jungle'?",
    answer: "Lion",
    category: "Nature",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "What is the capital of Iceland?",
    answer: "Reykjavik",
    category: "Geography",
    difficulty: "hard",
    used: false,
    reward_amount: 250,
  },

  {
    question: "Which blood type is known as the universal donor?",
    answer: "O Negative",
    category: "Science",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "Which continent has the most countries?",
    answer: "Africa",
    category: "Geography",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "Who was known as the 'Maid of Orléans'?",
    answer: "Joan of Arc",
    category: "History",
    difficulty: "hard",
    used: false,
    reward_amount: 250,
  },
  {
    question: "Which company developed the video game 'Fortnite'?",
    answer: "Epic Games",
    category: "Entertainment",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "What is the world’s largest land mammal?",
    answer: "African Elephant",
    category: "Nature",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "What is the capital of Switzerland?",
    answer: "Bern",
    category: "Geography",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "Who wrote 'Paradise Lost'?",
    answer: "John Milton",
    category: "Literature",
    difficulty: "hard",
    used: false,
    reward_amount: 250,
  },
  {
    question: "Which country hosted the first modern Olympics in 1896?",
    answer: "Greece",
    category: "History",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "Which animal can be seen on the Porsche logo?",
    answer: "Horse",
    category: "Miscellaneous",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "What is the capital of Brazil?",
    answer: "Brasília",
    category: "Geography",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },

  {
    question: "What metal is liquid at room temperature?",
    answer: "Mercury",
    category: "Science",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "Which language has the most native speakers worldwide?",
    answer: "Mandarin Chinese",
    category: "Language",
    difficulty: "hard",
    used: false,
    reward_amount: 250,
  },
  {
    question: "What does FIFA stand for?",
    answer: "Fédération Internationale de Football Association",
    category: "Sports",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question:
      "Which famous scientist introduced the idea of natural selection?",
    answer: "Charles Darwin",
    category: "Science",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "What year did World War I begin?",
    answer: "1914",
    category: "History",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "Which two elements make up water?",
    answer: "Hydrogen and Oxygen",
    category: "Science",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "Which city is known as the 'Eternal City'?",
    answer: "Rome",
    category: "Geography",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "What is the largest internal organ in the human body?",
    answer: "Liver",
    category: "Science",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "Which U.S. state is the Grand Canyon located in?",
    answer: "Arizona",
    category: "Geography",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "Who wrote 'Pride and Prejudice'?",
    answer: "Jane Austen",
    category: "Literature",
    difficulty: "hard",
    used: false,
    reward_amount: 250,
  },
  {
    question: "What is the capital of Argentina?",
    answer: "Buenos Aires",
    category: "Geography",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "Who developed the theory of relativity?",
    answer: "Albert Einstein",
    category: "Science",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "Which element has the atomic number 1?",
    answer: "Hydrogen",
    category: "Science",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "What is the world’s longest river?",
    answer: "Nile River",
    category: "Geography",
    difficulty: "hard",
    used: false,
    reward_amount: 250,
  },
  {
    question: "Which country is famous for the Great Pyramids?",
    answer: "Egypt",
    category: "History",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "Who was the first emperor of Rome?",
    answer: "Augustus",
    category: "History",
    difficulty: "hard",
    used: false,
    reward_amount: 250,
  },
  {
    question: "What is the main ingredient in guacamole?",
    answer: "Avocado",
    category: "Food",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "Which famous physicist was born in Pisa, Italy?",
    answer: "Galileo Galilei",
    category: "Science",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "What is the capital of Thailand?",
    answer: "Bangkok",
    category: "Geography",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "Which Shakespeare tragedy features King Lear?",
    answer: "King Lear",
    category: "Literature",
    difficulty: "hard",
    used: false,
    reward_amount: 250,
  },

  {
    question: "Which planet is nicknamed the 'Blue Planet'?",
    answer: "Earth",
    category: "Science",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "Who was the British Prime Minister during World War II?",
    answer: "Winston Churchill",
    category: "History",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "What is the capital of Kenya?",
    answer: "Nairobi",
    category: "Geography",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "Which painter is famous for cutting off part of his ear?",
    answer: "Vincent van Gogh",
    category: "Art",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "Which natural satellite orbits the Earth?",
    answer: "The Moon",
    category: "Science",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "What year did World War II end?",
    answer: "1945",
    category: "History",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "What is the capital of Turkey?",
    answer: "Ankara",
    category: "Geography",
    difficulty: "hard",
    used: false,
    reward_amount: 250,
  },
  {
    question: "What is the process by which plants make food?",
    answer: "Photosynthesis",
    category: "Science",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "Which sport is known as the 'king of sports'?",
    answer: "Soccer (Football)",
    category: "Sports",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "Who discovered penicillin?",
    answer: "Alexander Fleming",
    category: "Science",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },

  {
    question: "What is the capital of Portugal?",
    answer: "Lisbon",
    category: "Geography",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "Which element has the symbol 'Na'?",
    answer: "Sodium",
    category: "Science",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "Which explorer is credited with discovering America in 1492?",
    answer: "Christopher Columbus",
    category: "History",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "Who wrote 'Hamlet'?",
    answer: "William Shakespeare",
    category: "Literature",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "Which chemical element has the highest melting point?",
    answer: "Tungsten",
    category: "Science",
    difficulty: "hard",
    used: false,
    reward_amount: 250,
  },
  {
    question: "Which country gifted the Statue of Liberty to the USA?",
    answer: "France",
    category: "History",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "Which African country was formerly known as Abyssinia?",
    answer: "Ethiopia",
    category: "Geography",
    difficulty: "hard",
    used: false,
    reward_amount: 250,
  },
  {
    question: "What is the capital of South Africa?",
    answer:
      "Pretoria (administrative), Bloemfontein (judicial), Cape Town (legislative)",
    category: "Geography",
    difficulty: "hard",
    used: false,
    reward_amount: 250,
  },
  {
    question: "Which city hosted the 2008 Summer Olympics?",
    answer: "Beijing",
    category: "Sports",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "Which famous scientist worked with radioactivity?",
    answer: "Marie Curie",
    category: "Science",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },

  {
    question: "What is the national sport of Japan?",
    answer: "Sumo Wrestling",
    category: "Sports",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "Who was the first President of the United States?",
    answer: "George Washington",
    category: "History",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "Which is the largest country in the world by area?",
    answer: "Russia",
    category: "Geography",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "What is the boiling point of water in Celsius?",
    answer: "100°C",
    category: "Science",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "Who wrote 'The Divine Comedy'?",
    answer: "Dante Alighieri",
    category: "Literature",
    difficulty: "hard",
    used: false,
    reward_amount: 250,
  },
  {
    question: "Which ancient wonder was located in Babylon?",
    answer: "Hanging Gardens",
    category: "History",
    difficulty: "hard",
    used: false,
    reward_amount: 250,
  },
  {
    question: "What is the currency of Mexico?",
    answer: "Peso",
    category: "Geography",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "What gas do humans exhale when they breathe?",
    answer: "Carbon Dioxide",
    category: "Science",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "Which bird is the fastest in the world?",
    answer: "Peregrine Falcon",
    category: "Nature",
    difficulty: "hard",
    used: false,
    reward_amount: 250,
  },
  {
    question: "What year did the French Revolution begin?",
    answer: "1789",
    category: "History",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },

  {
    question: "Which country is known for inventing pizza?",
    answer: "Italy",
    category: "Food",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "What is the largest organ of the human body?",
    answer: "Skin",
    category: "Science",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  {
    question: "What is the capital of Hungary?",
    answer: "Budapest",
    category: "Geography",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "Which sea separates Europe and Africa?",
    answer: "Mediterranean Sea",
    category: "Geography",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "Who invented the telephone?",
    answer: "Alexander Graham Bell",
    category: "Technology",
    difficulty: "medium",
    used: false,
    reward_amount: 150,
  },
  {
    question: "Which U.S. state has the nickname 'The Sunshine State'?",
    answer: "Florida",
    category: "Geography",
    difficulty: "easy",
    used: false,
    reward_amount: 100,
  },
  // ... continues until 100
];
